version: '3.8'  # Specify the version of Docker Compose

services:
  web:  # Name of the service
    build:  # Build from the Dockerfile in the current context
      context: .  # Set the context to the current directory
    ports:
      - "5000:5000"  # Map port 5000 of the host to port 5000 of the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      FLASK_ENV: development  # Set the Flask environment to development
